name: "Test and Destroy WAF on CE using AWS Workflows"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
#  schedule:
#    - cron: '10 * * * *'
#    - cron: '30 * * * *'
    
jobs:
  terraform_schedule:
    name: "Test Actions Schedules"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./xc
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: bot-defense-re

      - name: Trigger Deploy workflow
        run: gh workflow run waf-on-ce-aws-apply.yml --ref deploy-waf-aws-ce
        if: github.event.schedule == '10 * * * *'
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_SECRET }}   

      - name: Trigger Destroy workflow
        run: gh workflow run waf-on-ce-aws-destroy.yml --ref destroy-waf-aws-ce
        if: github.event.schedule == '10 * * * *' 
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_SECRET }}  
          
      - name: Check EventName
        run: echo "event name is:" ${{ github.event_name }} 
        
      # - name: Add Email
      #   run: git config user.email @${{ github.actor }}

      # - name: Add Username
      #   run: git config user.name @${{ github.actor }}
  
      # - name: Create Empty Commit
      #   run: git commit --allow-empty -m "Empty commit4"
  
      # - name: Push Empty Commit
      #   run: git push origin bot-defense-re
      #   env:
      #     GH_TOKEN: ${{ secrets.ACTIONS_SECRET }}     
          
